- name: Install lightdm.conf
  become: yes
  copy:
          src: ../../etc/lightdm/lightdm.conf
          dest: /etc/lightdm/lightdm.conf
          backup: yes
          owner: root
          group: root
          mode: 0644

- name: Install lightdm-webkit2-greeter.conf
  become: yes
  copy:
          src: ../../etc/lightdm/lightdm-webkit2-greeter.conf
          dest: /etc/lightdm/lightdm-webkit2-greeter.conf
          backup: yes
          owner: root
          group: root
          mode: 0644

- name: Create greeter directory
  become: yes
  file:
          path: /usr/share/backgrounds/greeter
          state: directory
          owner: root
          group: root
          mode: 0755

- name: Install LightDM wallpaper
  become: yes
  copy:
          src: ../../usr/share/backgrounds/greeter/radpack_3.jpg
          dest: /usr/share/backgrounds/greeter/radpack_3.jpg
          backup: yes
          owner: root
          group: root
          mode: 0644

- name: Install LightDM dark style
  become: yes
  copy:
          src: ../../usr/share/lightdm-webkit/themes/material2-dark/
          dest: /usr/share/lightdm-webkit/themes/material2-dark/
          backup: yes
          owner: root
          group: root
